version: "3.8"
networks:
  stack:
services:
  postgresql:
    container_name: postgres
    image: postgres
    ports:
     - 5432:5432
    hostname: postgres-host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JAVA_MIN_MEM: 1g
      JAVA_MAX_MEM: 2g
    networks:
      - stack
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql 
